run:
  timeout: 5m
  modules-download-mode: readonly
  go: "1.21"

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gocritic
    - revive
    - gosec
    - unconvert
    - dupl
    - misspell
    - gocyclo
    - gocognit
    - prealloc
    - exportloopref
    - bodyclose
    - noctx
    - rowserrcheck
    - stylecheck
    - tparallel
    - thelper
    - unparam
    - wastedassign
    - nolintlint

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/LoriKarikari/compak
  govet:
    check-shadowing: true
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: indent-error-flow
      - name: errorf
      - name: superfluous-else
      - name: unreachable-code
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
      - opinionated
    disabled-checks:
      - hugeParam
      - rangeValCopy
      - appendCombine
  gocyclo:
    min-complexity: 15
  gocognit:
    min-complexity: 20
  dupl:
    threshold: 100
  gosec:
    excludes:
      - G204
      - G304
  stylecheck:
    checks: ["all", "-ST1000", "-ST1003"]
  unparam:
    check-exported: true

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - gocritic
    - path: cmd/
      linters:
        - gocyclo
        - gocognit
    - linters:
        - stylecheck
      text: "ST1000:"
    - linters:
        - revive
      text: "exported: exported .* should have comment or be unexported"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  unique-by-line: true
  sort-results: true