version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: compak
    main: ./cmd/compak
    binary: compak
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
      - windows_arm64
    ldflags:
      - -s -w
      - -X github.com/LoriKarikari/compak/internal/cli.version={{.Version}}
      - -X github.com/LoriKarikari/compak/internal/cli.commit={{.Commit}}

archives:
  - id: compak
    formats: [ 'tar.gz']
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE
  - id: compak-windows
    formats: [ 'zip']
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE
    ids:
      - compak

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

release:
  github:
    owner: LoriKarikari
    name: compak
  prerelease: auto
