services:
  nextcloud:
    image: nextcloud:30
    restart: unless-stopped
    ports:
      - "${port:-8080}:80"
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: ${db_password}
      NEXTCLOUD_ADMIN_USER: ${admin_user:-admin}
      NEXTCLOUD_ADMIN_PASSWORD: ${admin_password}
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: ${redis_password}
      NEXTCLOUD_TRUSTED_DOMAINS: localhost
    volumes:
      - nextcloud_data:/var/www/html
    depends_on:
      - db
      - redis

  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: ${db_password}
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4-alpine
    restart: unless-stopped
    command: redis-server --requirepass ${redis_password}
    volumes:
      - redis_data:/data

volumes:
  nextcloud_data:
  db_data:
  redis_data: