name: nextcloud
version: 30.0.0
description: Self-hosted file sharing and collaboration platform
author: compak-community
homepage: https://nextcloud.com

parameters:
  port:
    type: integer
    default: 8080
    description: "Port to expose Nextcloud on"

  admin_user:
    type: string
    default: admin
    description: "Nextcloud admin username"

  admin_password:
    type: string
    required: true
    description: "Nextcloud admin password"

  db_password:
    type: string
    required: true
    description: "Database password"

  redis_password:
    type: string
    required: true
    description: "Redis password for caching"