name: wordpress
version: 6.7.0
description: WordPress with MariaDB database
author: compak-community
homepage: https://wordpress.org

parameters:
  port:
    type: integer
    default: 8080
    description: "Port to expose WordPress on"

  db_password:
    type: string
    required: true
    description: "Database root password"

  db_name:
    type: string
    default: wordpress
    description: "WordPress database name"

  db_user:
    type: string
    default: wordpress
    description: "WordPress database user"