name: Sync Upstream Packages

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: Restore compose checksums cache
        uses: actions/cache@v4
        with:
          path: .cache/compose-checksums
          key: compose-checksums-${{ hashFiles('paks/*.yaml') }}
          restore-keys: |
            compose-checksums-

      - name: Check for upstream updates
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go run ./cmd/sync-upstream
